"use client";

import { useState, useEffect, useCallback } from "react";
import { getJobs, getCompanies, type JobFilters } from "@/lib/api";
import type { Job, Company } from "@/lib/types";
import { JobGrid } from "@/components/jobs/JobGrid";
import { JobFiltersPanel } from "@/components/jobs/JobFilters";

function StatPill({ value, label }: { value: string | number; label: string }) {
  return (
    <div className="flex items-center gap-2 px-4 py-2 rounded-full bg-white/10 backdrop-blur-sm border border-white/20">
      <span className="text-white font-bold text-sm">{value}</span>
      <span className="text-indigo-200 text-xs">{label}</span>
    </div>
  );
}

export default function HomePage() {
  const [jobs, setJobs] = useState<Job[]>([]);
  const [companies, setCompanies] = useState<Company[]>([]);
  const [total, setTotal] = useState(0);
  const [pages, setPages] = useState(0);
  const [loading, setLoading] = useState(true);
  const [filters, setFilters] = useState<JobFilters>({ page: 1, limit: 21 });
  const [sidebarOpen, setSidebarOpen] = useState(false);

  const loadJobs = useCallback(async (f: JobFilters) => {
    setLoading(true);
    try {
      const data = await getJobs(f);
      setJobs(data.items);
      setTotal(data.total);
      setPages(data.pages);
    } catch (e) {
      console.error("Failed to load jobs", e);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    getCompanies()
      .then((data) => setCompanies([...data.faang_plus, ...data.ai_startup]))
      .catch(console.error);
  }, []);

  useEffect(() => { loadJobs(filters); }, [filters, loadJobs]);

  const remoteCount = jobs.filter((j) => j.remote).length;

  return (
    <>
      {/* Hero */}
      <div className="bg-gradient-to-br from-indigo-600 via-indigo-700 to-violet-800 pt-12 pb-16">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="max-w-2xl mb-8">
            <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-white/10 border border-white/20 text-xs font-medium text-indigo-200 mb-5">
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse" />
              Live jobs · Refreshed every 6 hours
            </div>
            <h1 className="text-4xl sm:text-5xl font-extrabold text-white tracking-tight mb-4 leading-tight">
              Land your dream SWE role at<br />
              <span className="text-indigo-300">FAANG++ & AI startups</span>
            </h1>
            <p className="text-indigo-200 text-lg leading-relaxed">
              Real job listings with personalized AI interview prep — coding plans, system design, behavioral coaching, and insider company tips. Generated by Claude Opus.
            </p>
          </div>

          <div className="flex flex-wrap gap-3">
            {total > 0 && <StatPill value={total} label="SWE roles" />}
            <StatPill value="31" label="companies" />
            <StatPill value="5" label="prep types per job" />
            <StatPill value="Claude Opus" label="AI engine" />
          </div>
        </div>
      </div>

      {/* Main content */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 -mt-5">
        {/* Result bar */}
        <div className="flex items-center justify-between mb-5 bg-white rounded-2xl border border-slate-100 shadow-sm px-5 py-3">
          <div className="flex items-center gap-3">
            {!loading && (
              <p className="text-sm text-slate-600">
                <span className="font-bold text-slate-900">{total.toLocaleString()}</span> open roles
                {filters.q && <span className="text-indigo-600 ml-1">· "{filters.q}"</span>}
              </p>
            )}
          </div>
          {/* Mobile filter toggle */}
          <button
            onClick={() => setSidebarOpen(!sidebarOpen)}
            className="lg:hidden flex items-center gap-2 text-sm font-medium text-slate-600 hover:text-slate-900"
          >
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M3 4a1 1 0 011-1h16a1 1 0 011 1v2.586a1 1 0 01-.293.707l-6.414 6.414a1 1 0 00-.293.707V17l-4 4v-6.586a1 1 0 00-.293-.707L3.293 7.293A1 1 0 013 6.586V4z" />
            </svg>
            Filters
            {(filters.q || filters.level || filters.remote || filters.company || filters.tier) && (
              <span className="w-2 h-2 rounded-full bg-indigo-500" />
            )}
          </button>
        </div>

        <div className="flex gap-6 items-start pb-16">
          {/* Sidebar */}
          <div className={`w-56 flex-shrink-0 sticky top-20 ${sidebarOpen ? "block" : "hidden"} lg:block`}>
            <div className="card p-5">
              <JobFiltersPanel filters={filters} companies={companies} onChange={setFilters} />
            </div>
          </div>

          {/* Grid + pagination */}
          <div className="flex-1 min-w-0">
            <JobGrid jobs={jobs} loading={loading} />

            {pages > 1 && (
              <div className="flex items-center justify-center gap-2 mt-8">
                <button
                  onClick={() => setFilters((f) => ({ ...f, page: Math.max(1, (f.page || 1) - 1) }))}
                  disabled={(filters.page || 1) <= 1}
                  className="btn-ghost disabled:opacity-40 disabled:cursor-not-allowed px-5"
                >
                  ← Prev
                </button>
                <div className="flex items-center gap-1">
                  {Array.from({ length: Math.min(pages, 7) }, (_, i) => {
                    const p = i + 1;
                    const cur = filters.page || 1;
                    if (pages <= 7 || p === 1 || p === pages || Math.abs(p - cur) <= 1) {
                      return (
                        <button
                          key={p}
                          onClick={() => setFilters((f) => ({ ...f, page: p }))}
                          className={`w-9 h-9 rounded-xl text-sm font-medium transition-all ${
                            cur === p ? "bg-indigo-600 text-white shadow-sm" : "text-slate-600 hover:bg-slate-100"
                          }`}
                        >
                          {p}
                        </button>
                      );
                    }
                    if (p === 2 && cur > 4) return <span key={p} className="text-slate-300">…</span>;
                    if (p === pages - 1 && cur < pages - 3) return <span key={p} className="text-slate-300">…</span>;
                    return null;
                  })}
                </div>
                <button
                  onClick={() => setFilters((f) => ({ ...f, page: Math.min(pages, (f.page || 1) + 1) }))}
                  disabled={(filters.page || 1) >= pages}
                  className="btn-ghost disabled:opacity-40 disabled:cursor-not-allowed px-5"
                >
                  Next →
                </button>
              </div>
            )}
          </div>
        </div>
      </div>
    </>
  );
}
